### ISSUE TITLE
Where to find plugins dir

### ISSUE THREAD

**Issue by vb93** [tinwhisker/Owon-VDS1022#1]
Hi,
Where do I find ./plugins/org.eclipse.equinox.launcher_*.jar ?

**Comment by tinwhisker** [comment]
The wildcard implies that you replace it with the suitable file name.

You will find that only one file begins with "org.eclipse.equinox.launcher_" - use that one.

**Comment by tinwhisker** [comment]
And regards the issue title - the folder is found in the unpacked Owon zip (from Owon's site).

**Comment by tinwhisker** [comment]
Infact, everything is included and done in the OSX zip on the sources page.
