### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by Thermi** [tinwhisker/Owon-VDS1022#3]
Hi, I'm interested in getting an Owon USB scope, but I need to make sure I can use it on Linux first.
This "hack" looks extremely promising, but I wonder if it still works, so does it still work with the newest version?

**Comment by tinwhisker** [comment]
Hi Thermi.

The 'fix' was made after 1.0.23 was released, which is still the latest - so yes, it still works and i've had no need to update the repo.

It's not so-much a 'hack', as just giving the app the correct drivers and a way to run it.
In the case of OS X users, I wrap the Owen app with a bootstrap & icon to give it a 'native' feel.

Ok, so a 'hack' in the spirit of duct-tape and gum, than modification. This is deliberate to allow users to upgrade if/when a newer app is released (or to apply to other Owon apps?)

I haven't figured the issue on Linux yet - mainly through lack of time.

**Comment by Thermi** [comment]
Hi tinwhisker,

Thank you for the quick answer!
Okay, that's good to hear. In the mean time, I found the [sigrok](https://sigrok.org/) project, which provides drivers, firmwares and compatible software for scopes, including this one, so I guess one doesn't have to use Owon's software. Yes, I meant "hack" in the spirit of duct-tape and gum (that's why I use the double quotes). I guess I'll go for that - or another cheap scope and attempt to use sigrok with it. :)

**Comment by tinwhisker** [comment]
Can you find a link for the Sigrok to support the VDS? I can only find SDS support.

**Comment by Thermi** [comment]
You're right, it's not listed. I misremembered, sorry.

**Comment by GAZDOWN** [comment]
Hi Everyone, I've found this project: https://github.com/florentbr/OWON-VDS1022, it actually works like a charm on ArchLinux (KUDOS)

**Comment by tinwhisker** [comment]
> Hi Everyone, I've found this project: https://github.com/florentbr/OWON-VDS1022, it actually works like a charm on ArchLinux (KUDOS)

Yes! He did a good job.
While I prefer them being a neat 'app' style package like I did with the Mac, @florentbr has the time (and Linux knowledge) to make it work there - I've only recently gone full-time Linux, and use his build.
